name: retip
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  avatar_plus: ^0.0.5
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.1
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  meta: ^1.16.0
  on_audio_query:
    git:
      url: https://github.com/rozpo/on_audio_query
      path: packages/on_audio_query
      ref: main
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  talker_bloc_logger: ^5.0.0
  talker_flutter: ^5.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf
        - asset: assets/fonts/Play-Bold.ttf
          weight: 700
